# Generated by Django 4.2.7 on 2023-11-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.TextField(max_length=255)),
                ('query_name', models.TextField(max_length=255)),
                ('query_comentary', models.TextField(max_length=255)),
                ('is_top_term', models.BooleanField()),
                ('is_top_rising', models.BooleanField()),
                ('is_orderRank', models.BooleanField()),
                ('is_orderScore', models.BooleanField()),
                ('is_today', models.BooleanField()),
                ('es_date', models.DateField()),
                ('user_name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsersCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_com', models.TextField(max_length=255)),
                ('user_name', models.TextField(max_length=255)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userscom', to='bg_api.query')),
            ],
        ),
    ]
